CREATE SCHEMA IF NOT EXISTS retail;

CREATE TABLE IF NOT EXISTS retail.customers (
    customer_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL UNIQUE,
    full_name text NOT NULL,
    segment varchar(16) NOT NULL
        CHECK (segment IN ('consumer', 'business', 'vip')),
    registered_at timestamptz NOT NULL,
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS retail.addresses (
    address_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL REFERENCES retail.customers (customer_id),
    city text NOT NULL,
    region text NOT NULL,
    postal_code varchar(12) NOT NULL,
    address_type varchar(12) NOT NULL
        CHECK (address_type IN ('billing', 'shipping'))
);

CREATE TABLE IF NOT EXISTS retail.categories (
    category_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_category_id integer REFERENCES retail.categories (category_id),
    category_name text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS retail.products (
    product_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id integer NOT NULL REFERENCES retail.categories (category_id),
    sku varchar(24) NOT NULL UNIQUE,
    product_name text NOT NULL,
    price numeric(12, 2) NOT NULL CHECK (price > 0),
    brand text NOT NULL,
    attributes jsonb NOT NULL DEFAULT '{}',
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS retail.warehouses (
    warehouse_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_name text NOT NULL UNIQUE,
    region text NOT NULL,
    capacity integer NOT NULL CHECK (capacity > 0)
);

CREATE TABLE IF NOT EXISTS retail.inventory (
    warehouse_id integer NOT NULL REFERENCES retail.warehouses (warehouse_id),
    product_id bigint NOT NULL REFERENCES retail.products (product_id),
    quantity integer NOT NULL CHECK (quantity >= 0),
    reserved_quantity integer NOT NULL CHECK (
        reserved_quantity >= 0 AND reserved_quantity <= quantity
    ),
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (warehouse_id, product_id)
);

CREATE TABLE IF NOT EXISTS retail.customer_orders (
    order_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL REFERENCES retail.customers (customer_id),
    shipping_address_id bigint NOT NULL REFERENCES retail.addresses (address_id),
    order_status varchar(16) NOT NULL CHECK (
        order_status IN ('pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled')
    ),
    sales_channel varchar(12) NOT NULL
        CHECK (sales_channel IN ('web', 'mobile', 'store', 'marketplace')),
    ordered_at timestamptz NOT NULL,
    total_amount numeric(14, 2) NOT NULL CHECK (total_amount >= 0),
    discount_amount numeric(12, 2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0)
);

CREATE TABLE IF NOT EXISTS retail.order_items (
    order_id bigint NOT NULL REFERENCES retail.customer_orders (order_id),
    line_no smallint NOT NULL,
    product_id bigint NOT NULL REFERENCES retail.products (product_id),
    quantity smallint NOT NULL CHECK (quantity > 0),
    unit_price numeric(12, 2) NOT NULL CHECK (unit_price > 0),
    PRIMARY KEY (order_id, line_no)
);

CREATE TABLE IF NOT EXISTS retail.payments (
    payment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES retail.customer_orders (order_id),
    payment_method varchar(16) NOT NULL
        CHECK (payment_method IN ('card', 'cash', 'bank_transfer', 'wallet')),
    payment_status varchar(16) NOT NULL
        CHECK (payment_status IN ('authorized', 'captured', 'failed', 'refunded')),
    amount numeric(14, 2) NOT NULL CHECK (amount >= 0),
    paid_at timestamptz
);

CREATE TABLE IF NOT EXISTS retail.shipments (
    shipment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES retail.customer_orders (order_id),
    warehouse_id integer NOT NULL REFERENCES retail.warehouses (warehouse_id),
    carrier varchar(16) NOT NULL,
    tracking_number varchar(32) NOT NULL UNIQUE,
    shipment_status varchar(16) NOT NULL
        CHECK (shipment_status IN ('ready', 'in_transit', 'delivered', 'returned')),
    shipped_at timestamptz,
    delivered_at timestamptz,
    CHECK (delivered_at IS NULL OR delivered_at >= shipped_at)
);

