CREATE SCHEMA IF NOT EXISTS logistics;

CREATE TABLE IF NOT EXISTS logistics.suppliers (
    supplier_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name text NOT NULL,
    country_code char(2) NOT NULL,
    reliability_score numeric(4, 3) NOT NULL
        CHECK (reliability_score BETWEEN 0 AND 1),
    contract_since date NOT NULL,
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS logistics.facilities (
    facility_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_name text NOT NULL UNIQUE,
    facility_type varchar(16) NOT NULL
        CHECK (facility_type IN ('warehouse', 'hub', 'store', 'port')),
    region text NOT NULL,
    capacity_units integer NOT NULL CHECK (capacity_units > 0)
);

CREATE TABLE IF NOT EXISTS logistics.items (
    item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id bigint NOT NULL REFERENCES logistics.suppliers (supplier_id),
    sku varchar(24) NOT NULL UNIQUE,
    item_name text NOT NULL,
    item_class varchar(12) NOT NULL
        CHECK (item_class IN ('standard', 'fragile', 'cold', 'hazardous')),
    unit_weight_kg numeric(10, 3) NOT NULL CHECK (unit_weight_kg > 0),
    unit_value numeric(12, 2) NOT NULL CHECK (unit_value > 0),
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS logistics.purchase_orders (
    purchase_order_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id bigint NOT NULL REFERENCES logistics.suppliers (supplier_id),
    destination_facility_id integer NOT NULL
        REFERENCES logistics.facilities (facility_id),
    order_status varchar(16) NOT NULL CHECK (
        order_status IN ('draft', 'confirmed', 'in_transit', 'received', 'cancelled')
    ),
    priority varchar(12) NOT NULL
        CHECK (priority IN ('low', 'normal', 'high', 'critical')),
    ordered_at timestamptz NOT NULL,
    expected_at timestamptz NOT NULL,
    total_value numeric(14, 2) NOT NULL CHECK (total_value >= 0),
    CHECK (expected_at >= ordered_at)
);

CREATE TABLE IF NOT EXISTS logistics.purchase_order_lines (
    purchase_order_id bigint NOT NULL
        REFERENCES logistics.purchase_orders (purchase_order_id),
    line_no smallint NOT NULL,
    item_id bigint NOT NULL REFERENCES logistics.items (item_id),
    ordered_quantity integer NOT NULL CHECK (ordered_quantity > 0),
    received_quantity integer NOT NULL CHECK (
        received_quantity >= 0 AND received_quantity <= ordered_quantity
    ),
    unit_cost numeric(12, 2) NOT NULL CHECK (unit_cost > 0),
    PRIMARY KEY (purchase_order_id, line_no)
);

CREATE TABLE IF NOT EXISTS logistics.carriers (
    carrier_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrier_name text NOT NULL UNIQUE,
    service_level varchar(12) NOT NULL
        CHECK (service_level IN ('economy', 'standard', 'express')),
    base_rate numeric(10, 2) NOT NULL CHECK (base_rate > 0)
);

CREATE TABLE IF NOT EXISTS logistics.shipments (
    shipment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id bigint REFERENCES logistics.purchase_orders (purchase_order_id),
    carrier_id integer NOT NULL REFERENCES logistics.carriers (carrier_id),
    origin_facility_id integer NOT NULL REFERENCES logistics.facilities (facility_id),
    destination_facility_id integer NOT NULL REFERENCES logistics.facilities (facility_id),
    shipment_status varchar(16) NOT NULL CHECK (
        shipment_status IN ('created', 'picked_up', 'in_transit', 'delivered', 'exception')
    ),
    tracking_code varchar(32) NOT NULL UNIQUE,
    shipped_at timestamptz,
    promised_at timestamptz NOT NULL,
    delivered_at timestamptz,
    shipping_cost numeric(12, 2) NOT NULL CHECK (shipping_cost >= 0),
    CHECK (origin_facility_id <> destination_facility_id),
    CHECK (delivered_at IS NULL OR delivered_at >= shipped_at)
);

CREATE TABLE IF NOT EXISTS logistics.shipment_items (
    shipment_id bigint NOT NULL REFERENCES logistics.shipments (shipment_id),
    line_no smallint NOT NULL,
    item_id bigint NOT NULL REFERENCES logistics.items (item_id),
    quantity integer NOT NULL CHECK (quantity > 0),
    PRIMARY KEY (shipment_id, line_no)
);

CREATE TABLE IF NOT EXISTS logistics.tracking_events (
    tracking_event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id bigint NOT NULL REFERENCES logistics.shipments (shipment_id),
    facility_id integer REFERENCES logistics.facilities (facility_id),
    event_type varchar(20) NOT NULL CHECK (
        event_type IN ('label_created', 'departed', 'arrived', 'customs', 'delivered', 'exception')
    ),
    event_time timestamptz NOT NULL,
    event_payload jsonb NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS logistics.stock_movements (
    movement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id integer NOT NULL REFERENCES logistics.facilities (facility_id),
    item_id bigint NOT NULL REFERENCES logistics.items (item_id),
    movement_type varchar(12) NOT NULL
        CHECK (movement_type IN ('receipt', 'dispatch', 'transfer', 'adjustment')),
    quantity_delta integer NOT NULL CHECK (quantity_delta <> 0),
    reference_code varchar(32) NOT NULL,
    occurred_at timestamptz NOT NULL
);
